server:
  servlet:
    context-path: /practical
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:E:/AppData/Service/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
  rabbitmq:
    host: 192.168.3.18
    port: 5672
    username: lusiyi
    password: 123456
    publisher-confirm-type: correlated

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved